services:
  web:
    build: .
    command: python run.py # for development
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/link_shortener
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - MIGRATIONS_DIR=migrations
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app # for development
      - ./logs:/app/logs
      - ./migrations:/app/migrations
    networks:
      - app_net

  worker:
    build: .
    command: rq worker -u redis://redis:6379/0 link-shortener-tasks
    depends_on:
      - redis
    networks:
      - app_net
    environment:
      - REDIS_URL=redis://redis:6379/0

  scheduler:
    build: .
    command: rqscheduler -u redis://redis:6379/0 --interval 60
    depends_on:
      - redis
    networks:
      - app_net
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@db:5432/link_shortener

  db:
    ports:
      - "5432:5432"
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=link_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: always
    networks:
      - app_net

  tests:
    build: .
    command: pytest -s
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/link_shortener
      - REDIS_URL=redis://redis:6379/0
      - MIGRATIONS_DIR=migrations
    depends_on:
      - db
      - redis
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge