services:
  web:
    build: .
    command: python run.py # for development
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PYTHONPATH=/app
      - MIGRATIONS_DIR=migrations
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app # for development
      - ./logs:/app/logs
      - ./migrations:/app/migrations
    networks:
      - app_net

  worker:
    build: .
    command: rq worker -u redis://redis:6379/0 link-shortener-tasks
    depends_on:
      - redis
    networks:
      - app_net
    environment:
      - REDIS_URL=${REDIS_URL}

  scheduler:
    build: .
    command: rqscheduler -u redis://redis:6379/0 --interval 60
    depends_on:
      - redis
    networks:
      - app_net
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}

  db:
    ports:
      - "5432:5432"
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-data:/docker-entrypoint-initdb.d
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: always
    networks:
      - app_net

  tests:
    build: .
    command: pytest -s
    environment:
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - DATABASE_URL=${TEST_DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - MIGRATIONS_DIR=migrations
    depends_on:
      - db
      - redis
    volumes:
      - ./tests:/app/tests # for tests development
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge