services:
  web:
    build: .
    command: python run.py # for development
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/link_shortener
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app # for development
    networks:
      - app_net

  db:
    ports:
      - "5432:5432"
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=link_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-data:/docker-entrypoint-initdb.d
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: always
    networks:
      - app_net

  tests:
    build: .
    command: pytest -s
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/link_shortener
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - MIGRATIONS_DIR=migrations
    depends_on:
      - web
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge