name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    environment: development
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Build images
      run: docker compose build

    - name: Start services
      run: docker compose up -d db redis
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Run tests
      run: docker compose run --rm tests pytest -s
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
